// <auto-generated />
namespace com.jiechengbao.entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class DropColumn_Member_Asset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropColumn_Member_Asset));
        
        string IMigrationMetadata.Id
        {
            get { return "201607160458000_DropColumn_Member_Asset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
