// <auto-generated />
namespace com.jiechengbao.entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AlterColumn_Rules_TotalCredit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterColumn_Rules_TotalCredit));
        
        string IMigrationMetadata.Id
        {
            get { return "201607031128545_AlterColumn_Rules_TotalCredit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
