// <auto-generated />
namespace com.jiechengbao.entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddTable_MyAppointmentItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTable_MyAppointmentItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201607210626135_AddTable_MyAppointmentItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
